version: '3.8'

services:
  fl-finances-api:
    build: .
    ports:
      - "9999:9999"
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      AUDIENCE: ${AUDIENCE}
      ISSUER: ${ISSUER}
      REALM: ${REALM}
      SECRET: ${SECRET}